### ISSUE TITLE
Problem with sequence search (403)

### ISSUE THREAD

**Issue by sillitoe** [UCLOrengoGroup/cath-todo#14]
From: Lorenzo Di Rienzo

> I am trying to retrieve the cath domains on a dataset of protein sequences (attached) and to this purpose I followed the procedure as described in the API here: http://www.cathdb.info/search/by_sequence (Perl script). Despite some of my requests got a positive response in the past days, now i always get the following error message:
> "403 Forbidden..."

**Comment by sillitoe** [comment]
I'm having trouble replicating the 403 error message.

However, the service will return a "400 Bad Request" error when more than one sequence is submitted - this may be the source of the problem.

It used to be possible to scan with more than one input sequence, however I had to change this behaviour as the server was being swamped by overzealous searches (I should have documented this, sorry).

Can you check whether submitting one sequence at a time solves this problem for you?

**Comment by Lorenzo8** [comment]
I think that also whether you submit one sequence at a time the problem still remain. Even when I try with the example sequence in the API (manually) I can not get an answer. Anyway is there any other way to get the domain information for my sequence dataset?

**Comment by sillitoe** [comment]
Submitting a single sequence seems to work fine for me based on the latest version of code documented in the API. Perhaps something has changed since you wrote your script?

Can you confirm the URL of the endpoints you are using?

Might just be easier if you emailed the script you are using?

**Comment by sillitoe** [comment]
There was an error in the FASTA parsing section of your code - it was actually trying to submit more than one sequence at a time hence why the server was returning with a "forbidden" code.

I've added a comment here:

https://github.com/UCLOrengoGroup/cath-todo/commit/8a551d45e0adb18dec4e3d4763ae5ab901d435ff#diff-a509c4c83632bdc5d3936b6ca7af1545L42

The working version of the script is here:

https://github.com/UCLOrengoGroup/cath-todo/blob/master/gh_014/cath_task.pl

Please note, I've included the CPAN module [JSON::MaybeXS](https://metacpan.org/pod/JSON::MaybeXS) to convert the output from the web server into a data structure that we can understand in Perl. You will need to install this module yourself before you can run this version of the script.

**Comment by sillitoe** [comment]
Closing this for now - feel free to reopen if that fix doesn't solve the problem.
