### ISSUE TITLE
Improve documentation on CATH API

### ISSUE THREAD

**Issue by shouldsee** [UCLOrengoGroup/cath-todo#20]
Hi there CATH people,

Concerning pulling info from CATH as a www/public user, we feel the documentation of CATH-API is largely missing except for [sequence-based search](http://www.cathdb.info/search/by_sequence#api). I am interested in pulling info with a superfamily and could not find a clue about what request should look like. It'd be helpful if @sillitoe can point us to some starting point. (aka the format of url for generating .json responses?)

This issue is also meant to:
1. collect any effort in automating the documentation process. 
2. collect thoughts about API grammar in Python. @miruuna @ilsenatorov

Kind regards
Feng Geng
Summer Student

**Comment by sillitoe** [comment]
I've started some (unofficial) documentation here:

https://github.com/sillitoe/cath-api-docs

Please add issues to that repo if you need an endpoint that is not mentioned in that document.
