### ISSUE TITLE
Improve README of CATH's download page.

### ISSUE THREAD

**Issue by shouldsee** [UCLOrengoGroup/cath-todo#21]
@sillitoe 
On the [download](http://www.cathdb.info/download) page, I was trying to find the file the specifies the file formats for a CATH realease but failed to understand the documentation. Especially this sentence: 

> The names file follows the file format described in ./README-cath-names-file-format.txt (a.k.a. CNF format).

I will propose some formatting very soon.

BTW, regarding the ("CLF" format](http://download.cathdb.info/cath/releases/latest-release/cath-classification-data/README-cath-list-file-format.txt), the column 11 and column 12 (last two columns) are separated by only 1 spaces whereas other columns are separated by 4 or 5 spaces make it hard to specify delimiter for importing. Is this a desired feature or could we normalise the delimiter to say 5 spaces to allow easier parsing?

Update: Actually the file appear to be fixed-width rather than delimited, which presumably allows better visualisation. I have yet to figure out a route to import fix-width file into mysql.

```
Example:
--------
1oaiA00     1    10     8    10     1     1     1     1     1    59 1.000
1go5A00     1    10     8    10     1     1     1     1     2    69 999.000
1oksA00     1    10     8    10     2     1     1     1     1    51 1.800
1t6oA00     1    10     8    10     2     1     2     1     1    49 2.000
1cuk003     1    10     8    10     3     1     1     1     1    48 1.900
1hjp003     1    10     8    10     3     1     1     2     1    44 2.500
1c7yA03     1    10     8    10     3     1     1     2     2    48 3.100
1p3qQ00     1    10     8    10     4     1     1     1     1    43 1.700
1mn3A00     1    10     8    10     4     1     2     1     1    52 2.300
1nv8B01     1    10     8    10     5     1     1     1     1    71 2.200

````

Temporary regex solution for normalisation
```
match	replacement
"([0-9])\ ([0-9].*?\..*\n)"	"\1    \2"
"([0-9])    ([0-9])"	"\1     \2"

```

@nataliedawson : Following today's discussion, this is the format of file required to run the doped_cath pipeline. Preferably I would need the same file but for the complete CATH-B collection of s35-reps. (The s35-putative [file](http://download.cathdb.info/cath/releases/daily-release/newest/cath-b-s35-newest.gz) on "daily-release" from download page only contains the additional domains.) and is not in CLF format thus cannot be directly processed with the existing pipeline. UPDATE: Actually, I was wrong about the content of that file -- It indeeds contains all s35 in CATH-B!

**Comment by sillitoe** [comment]
Thanks for the README suggestion.

> Is this a desired feature or could we normalise the delimiter to say 5 spaces to allow easier parsing?

The columns are white space delimited, i.e. you just need to `split()` the string into columns allowing for one or more white space characters (`\s+`).
