### ISSUE TITLE
Request code review for IBIS mapping

### ISSUE THREAD

**Issue by sayonidas03** [UCLOrengoGroup/cath-todo#30]
#29 
[cath-funsite/funfams-IBIS_mapping/get_freq_score_cath_funfams.pl](https://github.com/sayonidas03/cath-funsite/blob/master/funfams-IBIS_mapping/get_freq_score_cath_funfams.pl)

**Comment by sillitoe** [comment]
this wasn't much of a "code review", but hopefully the alternative code is helpful.

https://github.com/sayonidas03/cath-funsite/pull/1
